from __future__ import annotations

import html
import re
import unicodedata
from pathlib import Path

import torch
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer


ROOT = Path(__file__).resolve().parent

BASE_MODEL = "Qwen/Qwen2.5-1.5B-Instruct"
ADAPTER_DIR = ROOT / "models" / "paper-qwen-lora" / "best_adapter"

MAX_TOTAL_CHARS = 3000


SYSTEM_PROMPT = """
You generate short academic research structures.

The user may provide the research topic in Korean.
Understand the Korean topic faithfully, but write the output in academic English.

IMPORTANT SEMANTIC RULE:

When the Korean topic refers to "음악저작물을 AI 학습데이터로 이용",
interpret it as:

"copyrighted musical works used as training data for generative AI"

Do NOT reinterpret it as:
"music generated by AI"
"AI-generated music used as training data"
"music created by AI systems"


CASE NAME RULE:

If the user explicitly provides a real case name, company name,
or party name in the research topic, you may repeat that name
only to define the scope or central case of the research.

Allowed example:

"This study centers on Concord Music Group et al. v. Anthropic
as the principal case for analysis."

This is allowed because it only identifies the research scope.

However, mentioning the case name does NOT authorize you
to generate factual information about that case.

Do NOT generate:
- the date of the case
- filing dates
- procedural history
- allegations
- claims made by either party
- actions performed by either party
- copyrighted works allegedly used
- quantities or statistics
- court decisions
- legal outcomes
- settlement information

These facts must remain unresolved until verified by external evidence.

The case name may be used as a research anchor,
but the facts of the case must not be invented.


YOUR ROLE:

Your role is structure only, not factual reporting.

Generate only:
- research purpose
- research questions
- scope of analysis
- analytical structure
- logical flow
- issues that should be verified
- factors that should be examined


DO NOT INVENT OR STATE:

- case facts
- dates
- court decisions
- legal outcomes
- statutes
- statistics
- party actions
- quotations
- citations
- URLs
- research findings


Do not describe what actually happened in a real case.

Instead explain:
- what the study aims to examine
- what facts should be verified
- what questions should be analyzed
- what factors should be compared
- how the research should proceed


Use cautious expressions such as:

"should be examined"
"should be verified"
"requires analysis"
"the study will consider"
"the analysis should evaluate"
"must be established through verified evidence"


Rules:

1. Write only in academic English.

2. Preserve the meaning and scope of the user's research topic.

3. A case name explicitly provided by the user may appear
   as the central case or research scope.

4. Do not infer or generate facts about that case.

5. Do not introduce unrelated technologies or cases.

6. Do not reinterpret copyrighted musical works used for AI training
   as AI-generated music.

7. Do not mention RAG, Transformer, LLM, retrieval,
   prompts, or internal system architecture.

8. Do not use markdown headings.

9. Do not use numbered or bullet lists.

10. Write complete academic sentences.

11. Do not output Korean, Chinese, Japanese,
    or mixed-script text.

12. Do not state final findings or legal conclusions.
"""


SECTION_CONFIG = {
    "title": {
        "instruction": """
Write one concise academic English title.

Preserve:
- the central research issue
- the case name explicitly provided by the user

The topic concerns copyrighted musical works used as training data
for generative AI.

Do not reinterpret the topic as AI-generated music.

Do not add:
- facts
- dates
- allegations
- judgments
- legal conclusions

Output only the title.
""",
        "max_new_tokens": 80,
        "char_limit": 240,
    },

    "abstract": {
        "instruction": """
Write exactly two complete academic sentences.

The first sentence should state the research purpose
and may identify the case explicitly provided by the user
as the central case of the study.

The second sentence should explain which factual and analytical
issues must be verified and examined.

The case name may be used only to define the research scope.

Do not describe:
- what happened in the case
- what either party did
- what either party claimed
- any court decision
- any date
- any legal result

Do not state findings.
Do not label the sentences.
""",
        "max_new_tokens": 150,
        "char_limit": 600,
    },

    "introduction": {
        "instruction": """
Write exactly three complete academic sentences.

Explain:
- the research problem
- the central research question
- the scope of the analysis

The case explicitly identified by the user may be named
as the central case of the study.

Do not describe:
- the history of the case
- the conduct of either party
- allegations
- claims
- dates
- court rulings
- legal outcomes

The case name is only a research-scope marker.

Do not state findings.
""",
        "max_new_tokens": 180,
        "char_limit": 750,
    },

    "body": {
        "instruction": """
Write exactly four complete academic sentences describing
the analytical structure of the main body.

The case explicitly identified by the user may be named
as the central case for analysis.

The first sentence should explain that the factual background
of the case must be verified through reliable external evidence.

The second sentence should explain that the positions
of the relevant parties must be identified from verified sources.

The third sentence should explain that relevant fair-use
considerations should be applied only after the necessary facts
have been verified.

The fourth sentence should explain that the relevant factors
should ultimately be evaluated together.

The case name may be used only as a scope marker.

Do not state:
- what either party actually did
- what either party argued
- allegations
- dates
- procedural history
- court outcomes
- factual conclusions
- legal conclusions

Do not use headings or lists.
""",
        "max_new_tokens": 220,
        "char_limit": 950,
    },

    "conclusion": {
        "instruction": """
Write exactly two complete academic sentences.

The case explicitly identified by the user may be referred to
as the central case of the research.

Explain that the final assessment must depend on verified evidence
and that unresolved factual issues must remain limitations.

Do not state:
- the actual outcome of the case
- liability
- infringement
- legality or illegality
- party claims
- court rulings
- factual findings

Do not state final findings.
""",
        "max_new_tokens": 140,
        "char_limit": 550,
    },
}


FACT_RISK_PATTERNS = [
    # 임의 날짜
    r"\b(?:19|20)\d{2}\b",

    # 소송/당사자 행동
    r"\bsued\b",
    r"\bwas sued\b",
    r"\bfiled (?:a |the )?(?:lawsuit|complaint)\b",
    r"\balleged that\b",
    r"\bclaimed that\b",
    r"\bclaimed fair use\b",
    r"\bargued that\b",
    r"\badmitted that\b",

    # 실제 행위를 단정
    r"\bcopied copyrighted\b",
    r"\bused copyrighted (?:works|music|material)\b",
    r"\btrained (?:its|the|a) model\b",
    r"\btrained on\b",
    r"\bunauthorized reproduction\b",
    r"\bunauthorized copying\b",
    r"\bsubstantial copying\b",

    # 판결
    r"\bthe court held\b",
    r"\bthe court ruled\b",
    r"\bcourt found\b",
    r"\bfound liable\b",
    r"\bwas found liable\b",
    r"\bwas liable\b",
    r"\binfringed\b",
    r"\bwas infringement\b",

    # 임의 연구 결과
    r"\bour findings\b",
    r"\bthe findings suggest\b",
    r"\bresults show\b",
    r"\bresults demonstrate\b",
    r"\bour results\b",

    # 구체 법조문 임의 생성
    r"\bsection\s+\d+\b",
    r"\bfair use act\b",

    # 기존 환각
    r"\bDALL[\s-]?E\b",
    r"\bStable Diffusion\b",
    r"\bGPT-\d",
    r"\bmusic-generated content\b",
    r"\bMGCs?\b",
]


SEMANTIC_RISK_PATTERNS = [
    r"\bAI-generated music\b",
    r"\bAI generated music\b",
    r"\bmusic generated by AI\b",
    r"\bmusic generated by artificial intelligence\b",
    r"\bmusic created by AI\b",
    r"\bmusic created by artificial intelligence\b",
    r"\bAI-generated musical works\b",
    r"\bAI generated musical works\b",
    r"\bmusic data generated by AI\b",
    r"\bmusic data created by AI\b",
]


EXPECTED_SENTENCE_COUNTS = {
    "abstract": 2,
    "introduction": 3,
    "body": 4,
    "conclusion": 2,
}


CJK_PATTERN = re.compile(
    r"[\u3040-\u30ff\u3400-\u4dbf\u4e00-\u9fff\uac00-\ud7a3]"
)


def _normalize_topic(topic: str) -> str:
    topic = html.unescape(topic or "")
    topic = unicodedata.normalize(
        "NFKC",
        topic,
    )

    topic = topic.replace(
        "\xa0",
        " ",
    )

    topic = topic.strip().strip(
        '"“”\'‘’'
    )

    topic = re.sub(
        r"[ \t]+",
        " ",
        topic,
    )

    topic = re.sub(
        r"\s*\n\s*",
        " ",
        topic,
    )

    return topic.strip()


def _clean_text(text: str) -> str:
    text = unicodedata.normalize(
        "NFKC",
        text or "",
    )

    text = html.unescape(text)

    text = text.replace(
        "\xa0",
        " ",
    )

    # Markdown heading 제거
    text = re.sub(
        r"(?m)^\s*#{1,6}\s*",
        "",
        text,
    )

    # 번호 / bullet 제거
    text = re.sub(
        r"(?m)^\s*(?:[-*]|\d+[.)]|[IVXLCDM]+[.)])\s+",
        "",
        text,
    )

    # Sentence 1: 같은 라벨 제거
    text = re.sub(
        r"(?i)\bSentence\s+\d+\s*:\s*",
        "",
        text,
    )

    # URL 제거
    text = re.sub(
        r"https?://\S+",
        "",
        text,
    )

    # DOI 제거
    text = re.sub(
        r"\bdoi\s*:\s*\S+",
        "",
        text,
        flags=re.IGNORECASE,
    )

    # 임의 인용 제거
    text = re.sub(
        r"\[(?:\d+)(?:\s*[-–,]\s*\d+)*\]",
        "",
        text,
    )

    # 공백 정리
    text = re.sub(
        r"[ \t]+",
        " ",
        text,
    )

    text = re.sub(
        r"\n{2,}",
        "\n",
        text,
    )

    return text.strip()


def _trim_complete_sentence(
    text: str,
    limit: int,
) -> str:
    text = _clean_text(
        text
    )

    if len(text) <= limit:
        return text

    cut = text[:limit]

    sentence_ends = [
        match.end()
        for match in re.finditer(
            r"[.!?](?=\s|$)",
            cut,
        )
    ]

    if sentence_ends:
        return cut[
            :max(sentence_ends)
        ].strip()

    space_pos = cut.rfind(
        " "
    )

    if space_pos > 0:
        return cut[
            :space_pos
        ].strip()

    return cut.strip()


def _contains_fact_risk(text: str) -> bool:
    for pattern in FACT_RISK_PATTERNS:
        if re.search(
            pattern,
            text,
            flags=re.IGNORECASE,
        ):
            return True

    return False


def _contains_semantic_risk(text: str) -> bool:
    for pattern in SEMANTIC_RISK_PATTERNS:
        if re.search(
            pattern,
            text,
            flags=re.IGNORECASE,
        ):
            return True

    return False


def _contains_cjk(text: str) -> bool:
    return bool(
        CJK_PATTERN.search(
            text
        )
    )


def _looks_corrupted(text: str) -> bool:
    """
    exa mined / th e / c opyr 같은
    단어 붕괴 탐지.
    """

    single_letters = re.findall(
        r"\b[b-hj-zB-HJ-Z]\b",
        text,
    )

    if len(single_letters) >= 2:
        return True

    broken_sequences = re.findall(
        r"\b[A-Za-z]{1,2}\s+"
        r"[A-Za-z]{1,2}\s+"
        r"[A-Za-z]{1,2}\b",
        text,
    )

    if len(
        broken_sequences
    ) >= 2:
        return True

    return False


def _sentence_count(text: str) -> int:
    text = text.strip()

    if not text:
        return 0

    sentences = re.split(
        r"(?<=[.!?])\s+(?=[A-Z])",
        text,
    )

    sentences = [
        sentence.strip()
        for sentence in sentences
        if sentence.strip()
    ]

    return len(
        sentences
    )


def _is_safe_output(
    text: str,
    section: str,
) -> bool:
    if not text.strip():
        return False

    # 사건 사실 환각
    if _contains_fact_risk(
        text
    ):
        return False

    # AI-generated music로 의미 뒤집힘
    if _contains_semantic_risk(
        text
    ):
        return False

    # 한중일 문자 혼용
    if _contains_cjk(
        text
    ):
        return False

    # 텍스트 깨짐
    if _looks_corrupted(
        text
    ):
        return False

    if section != "title":

        # 문장 완결성
        if text[-1] not in ".!?":
            return False

        # section별 문장 수
        expected = (
            EXPECTED_SENTENCE_COUNTS.get(
                section
            )
        )

        if expected is not None:
            actual = _sentence_count(
                text
            )

            if actual != expected:
                return False

    return True


def _safe_fallback(
    section: str,
) -> str:
    fallback = {
        "title": (
            "Fair-Use Analysis of Copyrighted Musical Works "
            "Used as Training Data for Generative AI"
        ),

        "abstract": (
            "This study aims to establish an analytical framework for "
            "examining copyrighted musical works used as training data "
            "for generative artificial intelligence. "
            "The research will identify the factual issues that require "
            "external verification and determine how relevant fair-use "
            "considerations should be applied to verified evidence."
        ),

        "introduction": (
            "The use of copyrighted musical works in generative AI training "
            "raises questions that require factual verification and legal analysis. "
            "This study will identify the central research question while treating "
            "the user-specified case as the principal scope of analysis. "
            "The analysis will distinguish verified evidence from unresolved "
            "case facts before applying the relevant fair-use considerations."
        ),

        "body": (
            "The factual background of the case should first be established "
            "through reliable external evidence. "
            "The positions of the relevant parties should then be identified "
            "from verified sources without assuming that disputed claims are true. "
            "The relevant fair-use considerations should subsequently be applied "
            "only to factual information that has been independently verified. "
            "Finally, those considerations should be evaluated together before "
            "any factual or legal conclusion is reached."
        ),

        "conclusion": (
            "The final assessment of the central case should depend on verified "
            "evidence and a combined evaluation of the relevant analytical considerations. "
            "Any unresolved date, allegation, party position, procedural fact, "
            "or legal outcome should remain an explicit limitation rather than "
            "being treated as established information."
        ),
    }

    return fallback[
        section
    ]


class PaperDraftGenerator:
    """
    입력:
        한국어 연구 주제

    출력:
        영어 논문 구조 초안

    허용:
        - 사용자 입력에 명시된 사건명
        - 사건을 연구 중심 사례로 지정
        - 연구 목적 / 연구 질문 / 분석 구조

    금지:
        - 사건 날짜
        - 당사자 실제 행위
        - 당사자 주장
        - 소송 경위
        - 판결
        - 통계
        - 출처
        - 최종 법적 결론
    """

    def __init__(self):
        if not ADAPTER_DIR.exists():
            raise FileNotFoundError(
                f"LoRA adapter not found: {ADAPTER_DIR}"
            )

        if not torch.cuda.is_available():
            raise RuntimeError(
                "CUDA GPU is not available."
            )

        self.tokenizer = (
            AutoTokenizer.from_pretrained(
                str(
                    ADAPTER_DIR
                ),
                trust_remote_code=True,
                use_fast=True,
            )
        )

        if (
            self.tokenizer.pad_token_id
            is None
        ):
            self.tokenizer.pad_token = (
                self.tokenizer.eos_token
            )

        base_model = (
            AutoModelForCausalLM.from_pretrained(
                BASE_MODEL,
                dtype=torch.float16,
                device_map="cuda",
                low_cpu_mem_usage=True,
                trust_remote_code=True,
            )
        )

        self.model = (
            PeftModel.from_pretrained(
                base_model,
                str(
                    ADAPTER_DIR
                ),
            )
        )

        self.model.eval()

    def _build_prompt(
        self,
        topic: str,
        section: str,
        retry: bool = False,
    ) -> str:
        cfg = SECTION_CONFIG[
            section
        ]

        retry_text = ""

        if retry:
            retry_text = """
Your previous answer was rejected.

Follow these rules strictly:

The case name explicitly provided by the user may be used
only as the central case or scope of the research.

Do not generate facts about the case.

Do not generate:
dates,
party actions,
party claims,
allegations,
procedural history,
court rulings,
statistics,
or legal outcomes.

Do not reinterpret copyrighted musical works
as AI-generated music.

Write only the academic research structure.

Follow the exact requested sentence count.
"""

        messages = [
            {
                "role": "system",
                "content": SYSTEM_PROMPT,
            },
            {
                "role": "user",
                "content": (
                    f"{cfg['instruction']}\n\n"
                    f"{retry_text}\n\n"
                    f"User research topic:\n"
                    f"{topic}\n\n"
                    "The topic is written in Korean. "
                    "Understand it faithfully, but answer only in English. "
                    "The real case name explicitly provided by the user "
                    "may be preserved as the central case of the research. "
                    "However, do not add factual information about that case. "
                    "All case facts must remain subjects for external verification. "
                    "When the topic concerns 음악저작물을 AI 학습데이터로 이용, "
                    "interpret it as copyrighted musical works used as "
                    "training data for generative AI. "
                    "Never reinterpret it as AI-generated music."
                ),
            },
        ]

        return (
            self.tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True,
            )
        )

    @torch.inference_mode()
    def _run_generation(
        self,
        topic: str,
        section: str,
        retry: bool = False,
    ) -> str:
        cfg = SECTION_CONFIG[
            section
        ]

        prompt = self._build_prompt(
            topic,
            section,
            retry,
        )

        inputs = self.tokenizer(
            prompt,
            return_tensors="pt",
        ).to(
            "cuda"
        )

        outputs = self.model.generate(
            **inputs,

            max_new_tokens=cfg[
                "max_new_tokens"
            ],

            do_sample=False,

            repetition_penalty=1.05,

            pad_token_id=(
                self.tokenizer.eos_token_id
            ),

            eos_token_id=(
                self.tokenizer.eos_token_id
            ),
        )

        generated = outputs[
            0,
            inputs[
                "input_ids"
            ].shape[1]:
        ]

        text = (
            self.tokenizer.decode(
                generated,
                skip_special_tokens=True,
            )
        )

        return (
            _trim_complete_sentence(
                text,
                cfg[
                    "char_limit"
                ],
            )
        )

    def _generate_section(
        self,
        topic: str,
        section: str,
    ) -> str:
        # 1차 생성
        text = self._run_generation(
            topic,
            section,
            retry=False,
        )

        if _is_safe_output(
            text,
            section,
        ):
            return text

        # 2차 생성
        retry_text = self._run_generation(
            topic,
            section,
            retry=True,
        )

        if _is_safe_output(
            retry_text,
            section,
        ):
            return retry_text

        # 두 번 실패하면 안전한 구조 문장 반환
        return _safe_fallback(
            section
        )

    def generate_draft(
        self,
        topic: str,
    ) -> dict:
        topic = _normalize_topic(
            topic
        )

        if not topic:
            raise ValueError(
                "topic must not be empty."
            )

        draft = {
            "title": (
                self._generate_section(
                    topic,
                    "title",
                ).strip(
                    '"“”'
                )
            ),

            "abstract": (
                self._generate_section(
                    topic,
                    "abstract",
                )
            ),

            "introduction": (
                self._generate_section(
                    topic,
                    "introduction",
                )
            ),

            "body": (
                self._generate_section(
                    topic,
                    "body",
                )
            ),

            "conclusion": (
                self._generate_section(
                    topic,
                    "conclusion",
                )
            ),
        }

        return draft


_generator: PaperDraftGenerator | None = None


def get_generator() -> PaperDraftGenerator:
    global _generator

    if _generator is None:
        _generator = (
            PaperDraftGenerator()
        )

    return _generator


def generate_draft(
    topic: str,
) -> dict:
    """
    Backend 공개 인터페이스.

    입력:
        한국어 연구 주제

    출력:
        영어 구조 초안

    반환 형식:
    {
        "title": str,
        "abstract": str,
        "introduction": str,
        "body": str,
        "conclusion": str
    }
    """

    return get_generator().generate_draft(
        topic
    )


if __name__ == "__main__":
    import json
    import sys

    topic = " ".join(
        sys.argv[1:]
    ).strip()

    if not topic:
        topic = (
            "생성형 AI 학습데이터로서 음악저작물 이용의 "
            "공정이용 판단기준 연구"
        )

    result = generate_draft(
        topic
    )

    print(
        json.dumps(
            result,
            ensure_ascii=False,
            indent=2,
        )
    )